name: desh_engineering_app_backend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  intl: ^0.19.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  clipboard: ^0.1.3
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  flutter_dropzone: ^4.0.3
  flutter_typeahead: ^5.2.0
  connectivity_plus: ^5.0.2
  multi_select_flutter: ^4.1.3
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3


  # Web Specific
  web: ^1.1.0
  http: ^1.2.2
  html: ^0.15.4
  fl_chart: ^0.69.0
  data_table_2: ^2.5.15
  url_strategy: ^0.3.0




  # State Manager
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  #-----------------LOCAL ASSETS----------------------#
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/animations/
    - assets/icons/payment_methods/

  #---------------LOCAL FONTS------------------------#
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Italic.ttf
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 800
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
